### ISSUE TITLE
some times Youtube video is not loaded first time

### ISSUE THREAD

**Issue by creotech** [lesha724/yii2-youtube-widget#1]
Hi,
Thanks for your widget.
some times new youtube  video url is not loaded first time.if refresh  the page then video is coming.please tell me how to prevent this.

**Comment by lesha724** [comment]
Hi, thanks. Can you show your code?

**Comment by creotech** [comment]
echo  Youtube::widget([
                'video'=>$singlePost->url, //youtube url.
                'iframeOptions'=>[
                    'class'=>'youtube-video'
                ],
                'divOptions'=>[
                    'class'=>'youtube-video-div'
                ],
                'height'=>420,
                'width'=>'100%',
                'playerVars'=>[
                      'autoplay' =>1,
                      'controls' =>1,
                      'showinfo' =>0,
                      'start'   =>0,
                      'end' =>0,
                      'loop ' =>1,
                      'modestbranding'=>1,
                      'fs'=>1,
                      'rel'=>0,
                      'disablekb'=>0,
                      'version'=>3,
                      'iv_load_policy'=>3,
                      'enablejsapi'=>1,
                      'autohide'=>1,
                      'cc_load_policy'=>1,
                ],
                'events'=>[
                    'onReady'=> 'function (event){
                                /*The API will call this function when the video player is ready*/
                              //  event.target.playVideo();
                    }',
                ]
            ]);
          }
         ?>

i am thinking this is because of youtube is not loading as our web page speed.

**Comment by lesha724** [comment]
May be try this

```php
<?= \lesha724\youtubewidget\Youtube::widget([
    'video'=>$singlePost->url, //youtube url.
    'iframeOptions'=>[
        'class'=>'youtube-video'
    ],
    'divOptions'=>[
        'class'=>'youtube-video-div'
    ],
    'height'=>420,
    'width'=>'100%',
    'playerVars'=>[
        'autoplay' =>1,
        'controls' =>1,
        'showinfo' =>0,
        'start' =>0,
        'loop ' =>1,
        'modestbranding'=>1,
        'rel'=>0,
        'iv_load_policy'=>3,
        'enablejsapi'=>1
    ]
]);
?>
```

**Comment by lesha724** [comment]
Sorry, I don`t know, why you have this problem. Your code works for me.
