### ISSUE TITLE
if we do refresh(ctrl + F5) multiple times that time video is not coming

### ISSUE THREAD

**Issue by creotech** [lesha724/yii2-youtube-widget#2]
Hi,

I am using Your suggested code only 

<?= \lesha724\youtubewidget\Youtube::widget([
    'video'=>$singlePost->url, //youtube url.
    'iframeOptions'=>[
        'class'=>'youtube-video'
    ],
    'divOptions'=>[
        'class'=>'youtube-video-div'
    ],
    'height'=>420,
    'width'=>'100%',
    'playerVars'=>[
        'autoplay' =>1,
        'controls' =>1,
        'showinfo' =>0,
        'start' =>0,
        'loop ' =>1,
        'modestbranding'=>1,
        'rel'=>0,
        'iv_load_policy'=>3,
        'enablejsapi'=>1
    ]
]);
?>
even after keeping static youtube link also getting same problem.this one is occured only if you are refreshed page with ctrl+F5.Please suggest me why it is happening.sorry for my english.

**Comment by lesha724** [comment]
Do you speak russian?

**Comment by creotech** [comment]
No i don't know Russian,I will explain one more time.
i am using your widget it is really good.Thanks for your widget.
but i am facing one issue with this.i.e some times youtube video is not coming.

The situation is when ever you are refreshing the page using ctrl+F5 that time video is not coming.. the following code is using...
please find the code

 echo \lesha724\youtubewidget\Youtube::widget([
     'video'=>$singlePost->url, //youtube url.
    'iframeOptions'=>[
        'class'=>'youtube-video'
    ],
    'divOptions'=>[
        'class'=>'youtube-video-div'
    ],
        'height'=>420,
    'width'=>'100%',
    'playerVars'=>[
        'autoplay' =>1,
        'controls' =>1,
        'showinfo' =>0,
        'start' =>0,
        'loop ' =>1,
        'modestbranding'=>1,
        'rel'=>0,
        'iv_load_policy'=>3,
        'enablejsapi'=>1
    ]
]);

**Comment by creotech** [comment]
if we are doing normal page refresh video is coming.but force refresh (ctrl+F5) this time video is not coming.

**Comment by igorkharchenko** [comment]
Hi,
  
I am facing the same problem.
Sometimes youtube video can't load normally and i need to refresh page.  
And sometimes chrome debugger shows me this message:
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://mysitelink.local')`  
I can't explain how you can reproduce this error, this error just shows to me, and I don't know real reason.

**Comment by lesha724** [comment]
@creotech , Can you show chrome debugger log?

**Comment by lesha724** [comment]
@IgorKharchenko , can you show your code?

**Comment by igorkharchenko** [comment]
@lesha724, I use modal window for play youtube video. Youtube events are not handled.

```php

use yii\bootstrap\Modal;
use lesha724\youtubewidget\Youtube;

?>

<?php Modal::begin([
    'id'           => 'barCode-modal-window',
    'header'       => '<h4>Где искать шильдик на приборе</h4>',
    'toggleButton' => [
        'label' => 'Где искать шильдик на приборе?',
        'class' => 'open-modal-window-link',
    ],
    'footer'       => 'Обучающее видео',
]);
?>

<p>Это видео научит вас, как найти шильдик на устройстве.</p>

<?php
echo Youtube::widget([
    'video' => 'https://www.youtube.com/watch?v=E9jWZRMMyjc',

    'iframeOptions' => [ /*for container iframe*/
                         'class' => 'youtube-video',
    ],
    'divOptions'    => [ /*for container div*/
                         'class' => 'youtube-video-div',
    ],
    'height'        => 390,
    'width'         => 560,
    'playerVars'    => [
        /*https://developers.google.com/youtube/player_parameters?playerVersion=HTML5&hl=ru#playerapiid*/
        /*	Значения: 0, 1 или 2. Значение по умолчанию: 1. Этот параметр определяет, будут ли отображаться элементы управления проигрывателем. При встраивании IFrame с загрузкой проигрывателя Flash он также определяет, когда элементы управления отображаются в проигрывателе и когда загружается проигрыватель:*/
        'controls'       => 0,
        /*Значения: 0 или 1. Значение по умолчанию: 0. Определяет, начинается ли воспроизведение исходного видео сразу после загрузки проигрывателя.*/
        'autoplay'       => 0,
        /*Значения: 0 или 1. Значение по умолчанию: 1. При значении 0 проигрыватель перед началом воспроизведения не выводит информацию о видео, такую как название и автор видео.*/
        'showinfo'       => 0,
        'start'          => 0,
        'end'            => 0,
        /*Значения: 0 или 1. Значение по умолчанию: 0. Если значение равно 1, то одиночный проигрыватель будет воспроизводить видео по кругу, в бесконечном цикле. Проигрыватель плейлистов (или пользовательский проигрыватель) воспроизводит по кругу содержимое плейлиста.*/
        'loop '          => 0,
        /*тот параметр позволяет использовать проигрыватель YouTube, в котором не отображается логотип YouTube. Установите значение 1, чтобы логотип YouTube не отображался на панели управления. Небольшая текстовая метка YouTube будет отображаться в правом верхнем углу при наведении курсора на проигрыватель во время паузы*/
        'modestbranding' => 1,
        /*Значения: 0 или 1. Значение по умолчанию 1 отображает кнопку полноэкранного режима. Значение 0 скрывает кнопку полноэкранного режима.*/
        'fs'             => 1,
        'rel'            => 0,
        /*Значения: 0 или 1. Значение по умолчанию: 0. Значение 1 отключает клавиши управления проигрывателем. Предусмотрены следующие клавиши управления.
            Пробел: воспроизведение/пауза
            Стрелка влево: вернуться на 10% в текущем видео
            Стрелка вправо: перейти на 10% вперед в текущем видео
            Стрелка вверх: увеличить громкость
            Стрелка вниз: уменьшить громкость
        */
        'disablekb'      => 0,
    ],
    'events'        => [

    ],
]);

Modal::end();
?>

```

**Comment by lesha724** [comment]
@IgorKharchenko, try [dev branch](https://github.com/lesha724/yii2-youtube-widget/tree/dev)

**Comment by creotech** [comment]
Hi,
This is My code
use yii\helpers\Html;
use yii\helpers\Url;
use lesha724\youtubewidget\Youtube;
use common\components\DefaultGlobals;
        if($singlePost->url){
        echo  Youtube::widget([
                'video'=>$singlePost->url,
              //  'video'=>'https://www.youtube.com/watch?v=53WBHajSO1k',
                'iframeOptions'=>[
                    'class'=>'youtube-video'
                ],
                'divOptions'=>[
                    'class'=>'youtube-video-div'
                ],
                'height'=>420,
                'width'=>'100%',
                'playerVars'=>[
                    'autoplay' =>1,
                    'controls' =>1,
                    'showinfo' =>0,
                    'start' =>0,
                    'loop ' =>1,
                    'modestbranding'=>1,
                    'rel'=>0,
                    'iv_load_policy'=>3,
                    'enablejsapi'=>1
                ],
            ]);
          }
i removed php tags for better displaying code here.

**Comment by creotech** [comment]
Hi,
I am getting this message in chrome debugg log

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://mydomainname').

**Comment by igorkharchenko** [comment]
@lesha724 Hi,
Tried to use dev-master and seems it works normally.  
But because I don't know the real reason of problem and how to reproduce this bug, I will follow for the further behavior of the widget and let you know if there are any bugs appear.  

Also on version 1.0.2 if video is not loaded, the console generates this errors every half-second:
[errors](https://image.prntscr.com/image/EXkOq8qbS6aWUOZwINbumw.png)  
(I use `player_wyoutube0` in other places on page)

**Comment by lesha724** [comment]
@IgorKharchenko, Можете показать код подключения скрипта order.js? 

Попробуйте указать при подключении ему опцию [POS_END](http://www.yiiframework.com/doc-2.0/yii-web-view.html#POS_END-detail). Так же посмотрите на возможное решение [здесь](https://stackoverflow.com/questions/41368785/youtube-iframe-embed-stopvideo-not-a-function).

**Comment by igorkharchenko** [comment]
@lesha724, Подключение скрипта `order.js`:  
```php
$this->registerJsFile(Url::to('/frontend/web/js/order.js', true), [
    'depends' => [yii\web\JqueryAsset::className()],
]);
```
`POS_END` здесь уже не поможет.  
  
Несколько дней никаких проблем не наблюдаю. Будем считать, что проблема решилась)  
p.s. предложенный вами вариант с `onYoutubeAPIReady` пока что не использовал, ибо и без него всё работает.
____________________
To english
Connection of script `order.js`:  
... code ...   
`POS_END` will not help here.  
  
I do not observe any problems for several days. We will assume that the problem has been resolved)
p.s. the variant you proposed with `onYoutubeAPIReady` has not yet been used, because now everything works without it.

**Comment by creotech** [comment]
Sorry I don't Know russian
