### ISSUE TITLE
Hi. Is it possible to make width parameter in percents?

### ISSUE THREAD

**Issue by icekem** [lesha724/yii2-youtube-widget#4]
Need to make width in percents (like 50%). 

If i try to write in widget - it doesn't works.

Maby you advice any possibility how to do this? Thanks.

Подскажите пожалуйста, возможно ли указывать ширину в процентах? (для iframe youtube это возможно).

Если указывать параметр - не работает.
Может подскажете как это можно сделать?

**Comment by lesha724** [comment]
@icekem , попробуйте указать 
```
'width'=>'50%',
```

**Comment by icekem** [comment]
Работает. Огромное спасибо.

А есть возможность как-то height назначить, чтобы соблюдался маштаб?

**Comment by lesha724** [comment]
Напрямую нет, т.к. width и height это просто атрибуты iframe, но можно с помощью js. Посмотрите [здесь](https://stackoverflow.com/questions/9975810/make-iframe-automatically-adjust-height-according-to-the-contents-without-using)

**Comment by icekem** [comment]
Спасибо большое! Очень нужный widget

**Comment by lesha724** [comment]
Пожалуйста!
